plugins {
    id 'java'
    id 'maven-publish'
    id 'fabric-loom' version "${loom_version}" apply(false)
}

allprojects {
    group = 'net.cucumberfabric'
    version = '1.0.0'

    repositories {
        mavenCentral()
        maven { url = 'https://repo.spongepowered.org/maven/' }
        maven { url = 'https://maven.fabricmc.net/' }
    }
}

subprojects {
    apply plugin: 'fabric-loom'
    apply plugin: 'java'

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.release.set(21)
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}